### ISSUE TITLE
Repo permissions

### ISSUE THREAD

**Issue by gautamvenugopalan** [CaltechExperimentalGravity/OptimalBragg#12]
@pacosalces do we want to make this repo public? Sean Leavey has already found some issues with the multiprocessing with python 3.12, but was unable to open an issue following the "Homepage" [link](https://github.com/CaltechExperimentalGravity/OptimalBragg/) from the [PyPi page](https://pypi.org/project/OptimalBragg/).

**Comment by pacosalces** [comment]
Done! I can't believe I forgot to do that ... Thanks for the heads up.
